### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Nogesma** [Nogesma/INF231-OCaml#1]
- [x] Finish part 5

- [x] Finish part 6

- [x] Add more asserts to include all possible cases
  - [x] sets.ml
  - [x] multiSets.ml
  - [x] refactor.ml
  - [x] contrepet.ml
  - [x] setOpti.ml

- [x] Find better var names
  - [x] sets.ml
  - [x] multiSets.ml
  - [x] refactor.ml
  - [x] contrepet.ml
  - [x] setOpti.ml

- [ ] Set type for functions
  - [x] sets.ml
  - [x] multiSets.ml
  - [x] refactor.ml
  - [x] contrepet.ml
  - [x] setOpti.ml

- [ ] Comment
  - [ ] sets.ml
  - [ ] multiSets.ml
  - [ ] refactor.ml
  - [ ] contrepet.ml
  - [ ] setOpti.ml
